### PR TITLE
Adding multilanguage system

### PR DESCRIPTION
**Pull request by Rubemlrm**
Added multi language system using laravel locales and sessions to handle the user selected language.
At the moment only have translations for PT and for En(only for the menus).
Added translations helpers on views.
Added SetLanguage middleware to persist the user selected language between requests.

This is a pull request relative to #13

### CODE REVIEW

**Comment by tomahock** [comment]
Great job! :D

**Comment by Rubemlrm** [comment]
Added new pull request to fix that, my bad. Sorry :/

**Comment by aariops** [comment]
hey @Rubemlrm  can you make another pull request with the previous batch of changes? since @tomahock reverted the initial changes, I can't access the translation files.

**Comment by aariops** [comment]
#27 :smile:

**Pull request merged**
